version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatbot_backend
    volumes:
      - ./backend:/app
      - ollama_data:/root/.ollama  # 持久化 Ollama 模型數據
    ports:
      - "8001:8001"    # Django API
      - "11435:11434"  # Ollama API
    environment:
      - OLLAMA_API_URL=http://localhost:11434/api/generate
    # 移除原來的 command，使用 Dockerfile 中的 CMD

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatbot_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # 避免 host node_modules 汙染 container
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # 為了讓 hot reload 在 Docker 裡正常
      - REACT_APP_API_URL=http://127.0.0.1:8001/api
    command: npm start

# 添加 volume 來持久化 Ollama 數據
volumes:
  ollama_data: